# **Practice 03: Data Types and Data Structures**

#### **Kelani Guyton**

---

**IMPORTANT**:
- Before starting the lab, save a copy to your google drive by navigating to `File > Save a copy in Drive` <br>

<br>


**Instructions**: Complete the lab below.

- <font color=red>Tasks</font> indicated in red must be completed to receive credit
- Include all code for your work
- Include markdown cells with written answers explaining your work when prompted
- **NOTE: Your completed lab must be submitted to Canvas as a .ipynb file by the end of the lab session**
---

<br>

####<font color=red>Organized</font>

**Answers should be organized in the following format for organization and readability**

<font color=red>Example task 1</font>

In [ ]:
# 1.

# This will be the code block to answer the first part of a task

1. This will be the text answer/explanation (if prompted) for the first task

<font color=red>Example task 2</font>

In [ ]:
# 2.

# This will be the code block to answer the second part of a task

2. This will be the text answer/explanation (if prompted) for the second task

<br>

Continue this format for the remaining subtasks

<br>

<br>

---

####<font color=red>Task 1</font> - Collecting data

Collect the following data from at least 4 of your neighbors
* Major
* Year in school (freshman, sophomore, etc.)
* Pets (`TRUE` or `FALSE` with no quotes)
* Name of one pet (if no pet, then use `NA` with no quotes)
* Hours slept night before


If members of your group would not like to provide certain information, that is okay! Simply enter `NA` in their entry

<font color=red>Task 1.1</font>  Create 5 vectors using `c()` for each of the variables (use variable names that are useful!)

In [12]:
#1.1

#vectors with sample data
major <- c("statistics", "psychology", "mathematics", "economics" )
year <-c("freshman", "senior", "sophomore", "freshman")
pets <- c(FALSE, TRUE, FALSE, TRUE)
pet_name <- c(NA, "petunia", NA, "rio")
sleep <- c(6, 7, 5, 6)

<font color=red>Task 1.2</font> Using the five vectors from Task 1.1, create a data frame and store the data frame as the variable `pets`.

In [13]:
#1.2

#creating data frame with pre-defined vectors
pets <- data.frame(major, year, pets, pet_name, sleep)

In [14]:
#data

pets

  major       year      pets  pet_name sleep
1 statistics  freshman  FALSE NA       6
2 psychology  senior     TRUE petunia  7
3 mathematics sophomore FALSE NA       5
4 economics   freshman   TRUE rio      6

<br>

<font color=red>Task 1.3</font> Use the `dim()` function to determine the number of observations and variables in the data frame `pets`.

In [15]:
dim(pets)

[1] 4 5

Observations is refering to the number of rows, which is 4. Variables is refering to the number of columns, which is 5.

<font color=red>Task 1.4</font> Use the `str()` function to determine which of the variables in the data frame are character data type.

<br>

In [16]:
#1.4

#check variable types
str(pets)

'data.frame':	4 obs. of  5 variables:
 $ major   : chr  "statistics" "psychology" "mathematics" "economics"
 $ year    : chr  "freshman" "senior" "sophomore" "freshman"
 $ pets    : logi  FALSE TRUE FALSE TRUE
 $ pet_name: chr  NA "petunia" NA "rio"
 $ sleep   : num  6 7 5 6

In [18]:
#checking a single column, we can use the $
str(pets$major)

 chr [1:4] "statistics" "psychology" "mathematics" "economics"

The variables classified as character are `major`, `year` and `pet_name`.

<font color=red>Task 1.5</font> Overwrite the names of the data frame to reflect the following:
  * `sdsu_major`
  * `school_year`
  * `pets_true_false`
  * `pet_name`
  * `sleep_hours`

In [21]:
#1.5

#overwrite column names
names (pets) <- c("sdsu_major", "school_year", "pet_true_false", "pet name", "sleep_hours")

#check
names(pets)

[1] "sdsu_major"     "school_year"    "pet_true_false" "pet name"
[5] "sleep_hours"

<br>

<font color=red>Task 1.6</font> Assign the name of each student as the row names of the data frame using the `rownames()` functions. Show the results to verify this was performed correctly.

In [22]:
#1.6

#assigning row names
row.names(pets) <- c("Minoree", "Dilynn", "Kayden", "Kairo")

In [23]:
#check
pets

        sdsu_major  school_year pet_true_false pet name sleep_hours
Minoree statistics  freshman    FALSE          NA       6
Dilynn  psychology  senior       TRUE          petunia  7
Kayden  mathematics sophomore   FALSE          NA       5
Kairo   economics   freshman     TRUE          rio      6

<br>

<br>

<br>

---

####<font color=red>Task 2</font> - Manipulating data types and coercion

<font color=red>Task 2.1</font>

1. Choose a number and assign it to a variable.
2. Check the data type of your variable using the `class()` function.
3. Convert the variable to a character using the `as.character()` function and reassign to the same variable.
4. Again, check the data type of your variable using the `class()` function.
5. In a text cell, write what you observe in complete sentences.

In [24]:
#2.1

#choosing a number & assigning to variable
k <- 12

In [25]:
#2.1.2

#check the default class of the variables
class(k)

[1] "numeric"

In [29]:
#2.1.3

#change type to character
k <- as.character(k)
k

[1] "12"

In [30]:
#2.1.4

#check class of variable
class(k)

[1] "character"

The value 12 was assigned to `k` was initially a numeric class. The function `as.character()` converted this `numeric` value to `character` class, as indicated by the apostrophes in the output.

<br>

<font color=red>Task 2.2</font>
1. Convert the number `1` into a logical data type using the `as.logical()` function. What are your observations?
2. Convert the number `-33.8` into a logical data type using the `as.logical()` function. What are your observations?
3. Convert the number `0` into a logical data type using the `as.logical()` function. What are your observations?
4. Convert the number `2.7` into an integer data type using the `as.integer()` function. What are your observations? Is this what you expected?

In [31]:
#2.2.1

#convert 1 to logical with `as.logical()`
as.logical(1)

[1] TRUE

We observed that 1 is returned as TRUE.

In [32]:
#2.2.2

#convert -33.8 to logical with `as.logical()`
as.logical(-33.8)

[1] TRUE

We observed that -33.8 is returned as TRUE.

In [33]:
#2.2.3

#convert 0 to logical with `as.logical()`
as.logical(0)

[1] FALSE

All nonzero numbers are converted to a `TRUE` logical. A zero is converted to a `FALSE` logical.

In [35]:
#2.2.4

#convert 2.7 to an integer
as.integer(2.7)

[1] 2

It appears the `as.integer` function rounds down ot the nearest integer.

<br>

<font color=red>Task 2.3</font>
1. Convert the character `"5.3"` into a `numeric` data type using the `as.numeric()` function. What are your observations?
2. Convert the character `"5.3"` into a `logical` data type using the `as.logical()` function. What are your observations?
3. Convert the character `"TRUE"` into a `logical` data type using the `as.logical()` function. What are your observations?
3. Convert the character `"5.3"` into an `integer` data type using the `as.integer()` function. What are your observations?
4. Create a character string of text of your favorite place to eat and attempt to convert the character into a `numeric` data type. What are your observations?

In [37]:
#2.3.1

#convert "5.3" to a numeric
as.numeric("5.3")

[1] 5.3

Numbers in `character` class form can be converted into there corresponding `numeric` class form.

In [38]:
#2.3.2

#convert "5.3" to a logical
as.logical("5.3")

[1] NA

Numbers in `character` form produce an `NA` when converted to a logical.

In [39]:
#2.3.3

#convert "TRUE" to a logical
as.logical("TRUE")

[1] TRUE

Logicals in `character` form can be converted into their corresponding `logical` class form.

In [40]:
#2.3.4

#convert "5.3" to an integer
as.integer("5.3")

[1] 5

Decimals in `character` class form can be coverted into their corresponding `integer` class resulting frmo the floor function (rounding down)

In [41]:
#2.3.5

#
as.numeric("the taco stand")

Warning message:
“NAs introduced by coercion”

[1] NA

Text in character class produces an `NA` when converted to `numeric` class

<br>

<font color=red>Task 2.4</font>
1. Convert the logical `TRUE` into a `numeric` data type using the `as.numeric()` function.  What are your observations?
2. Convert the logical `FALSE` into a `numeric` data type using the `as.numeric()` function.  What are your observations?
3. Convert the logical `TRUE` into a `character` data type using the `as.character()` function.  What are your observations?
4. Convert the logical `FALSE` into an `integer` data type using the `as.integer()` function.  What are your observations?

In [42]:
#2.4.1

as.numeric(TRUE)

[1] 1

A `TRUE` is equivalent to a `1` in `numeric` class.

In [43]:
#2.4.2

as.numeric(FALSE)

[1] 0

A `FALSE` is equivalent to a `0` in `numeric` class.

In [44]:
#2.4.3

as.character(TRUE)

[1] "TRUE"

A `TRUE` is equivalent to a `"TRUE"` in `character` class.

In [45]:
#2.4.4

as.integer(FALSE)

[1] 0

A `FALSE` is equivalent to a `0` in `integer` class.

<br>

<font color=red>Task 2.5</font>
1. Add a `character` data type to a `numeric` data type. What are your observations?
2. Add a `TRUE` logical to a `numeric` data type. What are you observations?
3. Add a `character` data type to a `logical` data type. What are your observations?

In [46]:
#2.5.1

#character + numeric
"7" + 12

ERROR: Error in "7" + 12: non-numeric argument to binary operator

We are unable to add a `character` class to a `numeric` class.

In [47]:
#2.5.2

#logical + numeric
TRUE + 6

[1] 7

Arithmetic operations with logicals consider a `TRUE` to be a value `1`.

In [48]:
#2.5.3

#character + logical
"32" + TRUE

ERROR: Error in "32" + TRUE: non-numeric argument to binary operator

Artithmetic operations with logicals consider `FALSE` to be a value `0` and `TRUE` to be `1`, but the operation produced an error since we are unable to add a `character` class to a `logical` class

<br>

<br>

<br>

<br>