# **Practice 12: Loops - Apply Family**

#### **Kelani Guyton**

---

**IMPORTANT**:
- Before starting the lab, save a copy to your google drive by navigating to `File > Save a copy in Drive` <br>

<br>


**Instructions**: Complete the lab below.

- <font color=red>Tasks</font> indicated in red must be completed to receive credit
- Include all code for your work
- Include markdown cells with written answers explaining your work when prompted
- **NOTE: Your completed lab must be submitted to Canvas as a .ipynb file by the end of the lab session**
---

<br>

####<font color=red>Organized</font>

**Answers should be organized in the following format for organization and readability**

<font color=red>Example task 1</font>

In [ ]:
# 1.

# This will be the code block to answer the first part of a task

1. This will be the text answer/explanation (if prompted) for the first task

<font color=red>Example task 2</font>

In [ ]:
# 2.

# This will be the code block to answer the second part of a task

2. This will be the text answer/explanation (if prompted) for the second task

<br>

Continue this format for the remaining subtasks

<br>

---

<br>

#### Packages

In [ ]:
# none

<br>

<br>

<br>

---

####<font color=red>Task 1</font> - Loading and Preprocessing the Dataset

<font color=red>Task 1.1</font> Today, we'll be working with salary data available online.

* Run the following script to load the salary dataset for today's assignment.

```
# load data frame
data_url                       <- "https://raw.githubusercontent.com/khasenst/datasets_teaching/refs/heads/main/salary_data.csv"
salary                         <- na.omit(read.csv(data_url, header = TRUE))

# convert character variables to factors
salary$Gender                  <- as.factor(salary$Gender)
salary$Education.Level         <- as.factor(salary$Education.Level)
salary$Job.Title               <- as.factor(salary$Job.Title)

# reassign levels
levels(salary$Education.Level) <-  c("missing", "BS", "BS", "HS",
                                     "MS", "MS", "PhD", "PhD")
salary$Education.Level         <- factor(salary$Education.Level, levels = c("missing", "HS", "BS", "MS", "PhD"))
```

In [1]:
# load data frame
data_url                       <- "https://raw.githubusercontent.com/khasenst/datasets_teaching/refs/heads/main/salary_data.csv"
salary                         <- na.omit(read.csv(data_url, header = TRUE))

# convert character variables to factors
salary$Gender                  <- as.factor(salary$Gender)
salary$Education.Level         <- as.factor(salary$Education.Level)
salary$Job.Title               <- as.factor(salary$Job.Title)

# reassign levels
levels(salary$Education.Level) <-  c("missing", "BS", "BS", "HS",
                                     "MS", "MS", "PhD", "PhD")
salary$Education.Level         <- factor(salary$Education.Level, levels = c("missing", "HS", "BS", "MS", "PhD"))

<br>

<font color=red>Task 1.2</font> View the first few lines of the `salary` data frame using the `head()` function.

In [3]:
head(salary)

  Age Gender Education.Level Job.Title         Years.of.Experience Salary
1 32  Male   BS              Software Engineer  5                   90000
2 28  Female MS              Data Analyst       3                   65000
3 45  Male   PhD             Senior Manager    15                  150000
4 36  Female BS              Sales Associate    7                   60000
5 52  Male   MS              Director          20                  200000
6 29  Male   BS              Marketing Analyst  2                   55000

<br>

<br>

<br>

---

####<font color=red>Task 2</font>

<font color=red>Task 2.1</font>

* Write a `for` loop that loops through each column in the `salary` data frame and prints the `class()` of each column

In [5]:
# method 1

# loop through each list item (i.e. column)
for(col in salary) {
  print(class(col))
}

[1] "integer"
[1] "factor"
[1] "factor"
[1] "factor"
[1] "numeric"
[1] "integer"

In [ ]:
# mehtod 2

# col as a numeric index
for(col in 1:ncol(salary)) {
  print(class(salary[, col]))
}

<br>

<font color=red>Task 2.2</font>

* Use `lapply()` to perform the same task from 2.1

In [6]:
print(lapply(salary, class))

$Age
[1] "integer"

$Gender
[1] "factor"

$Education.Level
[1] "factor"

$Job.Title
[1] "factor"

$Years.of.Experience
[1] "numeric"

$Salary
[1] "integer"

<br>

<font color=red>Task 2.3</font>

* Use `sapply()` to perform the same task from 2.1

In [8]:
print(sapply(salary, class))

                Age              Gender     Education.Level           Job.Title
          "integer"            "factor"            "factor"            "factor"
Years.of.Experience              Salary
          "numeric"           "integer"

<br>

<font color=red>Task 2.4</font>

* In a text cell, compare the outputs Tasks 2.1-2.3

The different loops perform the same operation, but the outputs are in different formats. The `for` loop simply prints the statement, unless we store the output as a vector. The `lappy()` output is an unstructuctured list. The `sapply()` output is a character vector.

<br>

---

####<font color=red>Task 3</font>

<font color=red>Task 3.1</font>

* Store the columns of `salary` that are either `integer` or `numeric` class into another data frame called `salary_numeric`

In [9]:
salary_numeric <- salary[, sapply(salary, class) %in% c("integer", "numeric")]

# check
head(salary_numeric)

  Age Years.of.Experience Salary
1 32   5                   90000
2 28   3                   65000
3 45  15                  150000
4 36   7                   60000
5 52  20                  200000
6 29   2                   55000

<br>

<font color=red>Task 3.2</font>

* Use `apply()` to calculate the average of each column in `salary_numeric`

In [10]:
print(apply(salary_numeric, 2, mean))

                Age Years.of.Experience              Salary
       3.362203e+01        8.095014e+00        1.153270e+05

<br>

---

####<font color=red>Task 4</font>

<font color=red>Task 4.1</font>

* Create a function called `calc_metrics` that calculates the mean and standard deviation of `numeric` or `integer` vector

* The function should return the mean and standard deviation as a vector of length 2 using the `c()` function

In [13]:
calc_metrics <- function(vec) {
  # calculate mean
  m <- mean(vec)
  # standard deviation
  s <- sd(vec)

  return(c(m, s))
}

<br>

<font color=red>Task 4.2</font>

* Use the `tapply()` function to calculate the mean and standard devation of salary for each unique education level

* What is the `class()` of the output?

In [14]:
tapply(salary$Salary, salary$Education.Level, calc_metrics)

$missing
[1] 1e+05    NA

$HS
[1] 36706.69 22549.13

$BS
[1] 95082.91 44091.79

$MS
[1] 130112.06  40640.82

$PhD
[1] 165651.46  34339.75

The class of the output is an unstructured list.

<font color=red>Task 4.3</font>

* Use `do.call()` to "row bind" the output from Task 4.2

In [15]:
do.call(rbind, tapply(salary$Salary, salary$Education.Level, calc_metrics))

        [,1]      [,2]
missing 100000.00       NA
HS       36706.69 22549.13
BS       95082.91 44091.79
MS      130112.06 40640.82
PhD     165651.46 34339.75

<br>

<font color=red>Task 4.4</font>

Convert your output from Task 4.3 into a data frame called `data_summary` with the following attributes:

* The data frame should have 2 columns. One column should be named `salary_mean` and the other column should be named `salary_sd`.

In [16]:
# makes metrix with values from `calc_metrics()`
data_summary <- do.call(rbind, tapply(salary$Salary, salary$Education.Level, calc_metrics))

# overwrite matrix to data frame
data_summary <- data.frame(data_summary)

# rename the columns
names(data_summary) <- c("salary_mean", "salary_sd")

# check
data_summary

        salary_mean salary_sd
missing 100000.00         NA
HS       36706.69   22549.13
BS       95082.91   44091.79
MS      130112.06   40640.82
PhD     165651.46   34339.75

<br>

<br>

<br>

---

####<font color=red>Task 5</font>

<font color=red>Task 5.1</font>

* Repeat Task 4, except using `Age` instead of `Salary` and `Job.Title` instead `Education.Level`

In [20]:
# making the matrix with mean & standard deviations
data_summary <- do.call(rbind, tapply(salary$Age, salary$Job.Title, calc_metrics))

# convert matrix to data frame
data_summary <- data.frame(data_summary)

# rename the columns
names(data_summary) <- c("age_mean", "age_sd")

# check
data_summary

                                 age_mean age_sd
Account Manager                  32.00000        NA
Accountant                       31.00000        NA
Administrative Assistant         37.50000 2.1213203
Back end Developer               30.93443 5.9742075
Business Analyst                 33.50000 0.7071068
Business Development Manager     34.00000        NA
Business Intelligence Analyst    33.00000        NA
CEO                              50.00000        NA
Chief Data Officer               44.00000        NA
Chief Technology Officer         52.00000        NA
Content Marketing Manager        38.46575 9.0093812
Copywriter                       28.00000        NA
Creative Director                42.00000        NA
Customer Service Manager         44.50000 9.1923882
Customer Service Rep             27.00000        NA
Customer Service Representative  26.66667 2.6583203
Customer Success Manager         28.00000        NA
Customer Success Rep             26.00000        NA
Data Analyst                     28.68595 4.3354502
Data Entry Clerk                 25.00000        NA
Data Scientist                   36.06402 7.1443931
Delivery Driver                  24.00000 0.0000000
Developer                        27.00000        NA
Digital Content Producer         30.00000        NA
Digital Marketing Manager        32.13462 6.7418181
Digital Marketing Specialist     29.33333 0.4879500
Director                         52.00000        NA
Director of Business Development 47.00000        NA
Director of Data Science         44.47368 3.5862100
Director of Engineering          46.00000 1.4142136
⋮                                ⋮        ⋮
Senior Research Scientist        37.20408 2.1309191
Senior Researcher                46.00000        NA
Senior Sales Manager             45.50000 2.1213203
Senior Sales Representative      39.50000 0.7071068
Senior Scientist                 40.00000 3.4641016
Senior Software Architect        37.00000        NA
Senior Software Developer        38.00000 6.0827625
Senior Software Engineer         39.88115 6.4576981
Senior Training Specialist       40.00000        NA
Senior UX Designer               44.66667 0.5773503
Social Media Man                 26.00000        NA
Social Media Manager             26.64286 1.0818178
Social Media Specialist          28.00000        NA
Software Developer               26.90400 2.2768966
Software Engineer                28.31853 2.6176170
Software Engineer Manager        45.74202 8.3583054
Software Manager                 37.00000        NA
Software Project Manager         37.00000        NA
Strategy Consultant              41.00000        NA
Supply Chain Analyst             50.00000        NA
Supply Chain Manager             43.00000        NA
Technical Recruiter              36.00000        NA
Technical Support Specialist     28.00000        NA
Technical Writer                 27.00000        NA
Training Specialist              39.00000        NA
UX Designer                      34.00000        NA
UX Researcher                    27.00000        NA
VP of Finance                    47.00000        NA
VP of Operations                 47.00000        NA
Web Developer                    30.52874 4.0543949

<br>

<font color=red>Task 5.2</font>

* Order the summary from Task 5.1 in increasing order

* Which jobs have the youngest individuals on average? List the first two.

In [21]:
head(data_summary[order(data_summary$age_mean, decreasing = FALSE), ], 3)

                 age_mean age_sd
Receptionist     23.64912 0.7194052
Delivery Driver  24.00000 0.0000000
Junior Developer 24.00000        NA

The youngest individuals on average have the jobs receptionist, delivery driver, and junior developer.

<br>